services:
  - type: web
    name: pocket-terminal
    env: node
    plan: free
    healthCheckPath: /healthz
    buildCommand: bash ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: TERMINAL_PASSWORD
        sync: false
        description: "The password used to unlock the web terminal"
